### ISSUE TITLE
some PIC32MZXXXX files have symbol names not compatible with linux file system

### ISSUE THREAD

**Issue by rimmartin** [erichVK5/translate2geda#1]
Hi, errors because symbol name

```
There was an error saving: PIC32MZXXXXEC(G/H/M)144-I/PH.sym
java.io.FileNotFoundException: PIC32MZXXXXEC(G/H/M)144-I/PH.sym (No such file or directory)

```
when proccesing PIC32/PIC32MZXXXXEF\(G\&slash_H\&slash_M\)144-I\&slash_PH.bxl
from microchip download

**Comment by erichVK5** [comment]
Fixed and tested on the offending BXL file.

Not sure who at Microchip decided slashes in filenames were a good idea, but it is fixed now.

Thanks for flagging the problem.

Regards,

Erich.
