### ISSUE TITLE
javac compile error 

### ISSUE THREAD

**Issue by zorgrian** [erichVK5/translate2geda#2]
Hi,

I have tried compiling the source files with javac. Unfortunately the following error is thrown out...

Note: Plotter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Ok so I compiled again with -Xlint unchecked to get more info... this is the result

HersheySansFontClass.java:391: warning: [cast] redundant cast to long
    long renderedWidth = (long)(renderedWidthCentimil());
                         ^
HersheySansFontClass.java:456: warning: [cast] redundant cast to long
        TrX1 = (long)(strokes[i] - (width(c) - kerning(c))/2);
               ^
HersheySansFontClass.java:457: warning: [cast] redundant cast to long
        TrY1 = (long)(strokes[i+1] + yCentredOffset());
               ^
HersheySansFontClass.java:458: warning: [cast] redundant cast to long
        TrX2 = (long)(strokes[i+2] - (width(c) - kerning(c))/2);
               ^
HersheySansFontClass.java:459: warning: [cast] redundant cast to long
        TrY2 = (long)(strokes[i+3] + yCentredOffset());
               ^
SymbolPin.java:271: warning: [cast] redundant cast to long
    return (long)(mmTextToNM(mmValue)/25400);
           ^
Plotter.java:135: warning: [rawtypes] found raw type: Vector
    Vector     cmdVector;// Vector containing all single commands and tokens
    ^
  missing type arguments for generic class Vector<E>
  where E is a type-variable:
    E extends Object declared in class Vector
Plotter.java:353: warning: [rawtypes] found raw type: Vector
	cmdVector = new Vector();	// New command vector
	                ^
  missing type arguments for generic class Vector<E>
  where E is a type-variable:
    E extends Object declared in class Vector
Plotter.java:618: warning: [unchecked] unchecked call to insertElementAt(E,int) as a member of the raw type Vector
            cmdVector.insertElementAt(st.nextToken(), pos++);
                                     ^
  where E is a type-variable:
    E extends Object declared in class Vector
9 warnings

**Comment by zorgrian** [comment]
Note that 'Plotter.java' is the main problem here as it will not compile with cmdVector declared as it is.
JAVAC does not like compiling this and I am not a java expert so either the problem needs to be fixed (best) or another java compiler might be used that is more forgiving.

Having looked at the code (even though I'm not an Java expert) I see that its possible that any compiler might take exception to this declaration (or lack of it)

**Comment by erichVK5** [comment]
Thanks for the sleuthing.

I have repurposed the Plotter code from another author written circa 1999-2000, and never got around to fixing the warnings, since it still works OK, despite the warnings.

You have inspired me to have another look at it. It will be a couple of weeks before I have the time to do it, due to a fairly punishing schedule at present.

Thanks again,

Erich.

**Comment by zorgrian** [comment]
Yeah, OK I can get javac to make a runtime file. However, I cannot seem to get this to actually translate .asc files into .sch (geda) files properly. It ends up with a one line piece of text:
v 20110115 1

Please let me know what you think I have done wrong (if anything) as I would really like to use this code.

I was considering writing a converter in python...

**Comment by erichVK5** [comment]
I tested a file found randomly on the net and it was encoded in ISO-8859-15 text format.

This seems to make java's hasNext() line parser misbehave in the Scanner object.

I did all my testing with locally generated LT Spice files so did not come across this issue. Thanks for finding it!!!

I will see how to remedy it, but until then, all you need to do is:

Save your .asc file in utf-8, and it should work fine. 

Let me know how you go.

P.S. Don't forget to put the LT-Spice geometry compatible footprints in your gschem symbol search path.

I'll update the README.

**Comment by erichVK5** [comment]
The Plotter.java warnings have been fixed now.

I will close the issue relating to the Plotter.java warnings.
