### ISSUE TITLE
deprecated constructors

### ISSUE THREAD

**Issue by ugokanain** [erichVK5/translate2geda#3]
Plotter.java is using  new Double and new Integer constructors. These should be changed to Double.valueOf instead. 

For instance Double d = new Double(0.0); should be Double d = Double.valueOf(0.0) and the other similar cases. So should Integer i = Integer.valueOf(0);

**Comment by erichVK5** [comment]
Thank you. I will revise when I get a spare moment.

The Plotter code dates back to 2000, IIRC, and has some quaint bits.

Regards,

Erich.

**Comment by erichVK5** [comment]
Thanks for the bug report. Fixed!
