### ISSUE TITLE
add a folder out option

### ISSUE THREAD

**Issue by easyw** [erichVK5/translate2geda#4]
is it possible to add a parameter to specify the destination folder for the converted files?
something like:
`java translate2geda someFile.lbr [-o folder_dir]`
Thanks
Maurice

**Comment by erichVK5** [comment]
If you freshen up your local copy, you can try:

java translate2geda someFile.lbr -o folder_dir/path/to/somewhere/

you need to add the slash(es), so the code doesn't need to guess what platform you're on

It seems to work, based on a quick test

Cheers,

Erich.

**Comment by easyw** [comment]
@erichVK5 
it just works like a charm!
many thanks 😄
