### ISSUE TITLE
Unicode breaks build with openjdk-11

### ISSUE THREAD

**Issue by ldoolitt** [erichVK5/translate2geda#5]
Attempting a trasnslate2geda build using stock Debian Buster (`apt-get install default-jdk`, openjdk 11.0.4) gives me literally 100 errors of the form
  `SymbolText.java:35: error: unmappable character (0xE2) for encoding US-ASCII`
  `//??? orientation = horizontal orientation (=0) or vertical (=1).`

Replacing all the unicode bullets (U+2022) with some ASCII placeholder removes the problem, without affecting functionality because they are all only found in comments.

A one-liner to make that happen is
   `for f in Symbol*.java; do sed -i -e 's/•/*/g' $f; done`
where the character after the first slash in s/•/*/g is the offending U+2022.

After that simple change, my build of `translate2geda` appears basically functional.

**Comment by erichVK5** [comment]
Fixed, in the great unicode bullet (U+2022) purge of 2022.
