### ISSUE TITLE
java error with LTspice file

### ISSUE THREAD

**Issue by 122christo** [erichVK5/translate2geda#7]
I 've tried to use translate2geda with a Ltspice file, but got this error:

christoph@chris:~/translate2geda$ java translate2geda Lt1011_osc.asc
Using filename: Lt1011_osc.asc
Hmm, that didn't work. Probably a file IO issue:
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 2

Whats going on? How to fix it?

Thanks for reading and helping!

**Comment by 122christo** [comment]
OK, i found the eror.
I had too complicated voltage sources in my Ltspice Sim.
Now it works.

**Comment by erichVK5** [comment]
Cool, glad to hear it is behaving now.

Erich.
