### ISSUE TITLE
"onsolder" flag not set correctly 

### ISSUE THREAD

**Issue by t0mpr1c3** [erichVK5/translate2geda#8]
When converting e.g. https://github.com/SimonMerrett/SOICbite/blob/master/SOICbite_Eagle.lbr, pads 5-8 do not appear on the far side of the board because the "onsolder" flag is not set.

**Comment by erichVK5** [comment]
I will try and fix this when I get a spare moment.

Thanks for the bug report.

**Comment by erichVK5** [comment]
Now fixed, with alterations to Pad.java Eagle XML parser

Thanks for the bug report
